import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Cursor from "@/components/Cursor";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material'
import { theme } from '@/styles/theme'

import '../assets/icons/generated-icons.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
        <Cursor/>
      </body>
    </html>
  );
}
